# Generated by Django 4.0.5 on 2022-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='mode',
            field=models.CharField(default='spent', max_length=12),
        ),
        migrations.AddField(
            model_name='dtype',
            name='mode',
            field=models.CharField(default='spent', max_length=12),
        ),
    ]
